import type { SketchParamDefinition } from '../../core/types';

export const MOFO_CUBE_PARAMS: SketchParamDefinition[] = [
    // --- SEKCJA 1: POZYCJA I ORIENTACJA ---
    {
      key: 'z_position',
      label: 'Tunnel Z Pos',
      type: 'number',
      min: -2000,
      max: 800,
      step: 1,
      defaultValue: 0,
    },
    {
      key: 'Crazy_z_position',
      label: 'Z Warp (Crazy)',
      type: 'number',
      min: -50,
      max: 50,
      step: 1,
      defaultValue: 0,
    },
    {
      key: 'rotationSpeed',
      label: 'Auto-Rot Speed',
      type: 'number',
      min: 0,
      max: 10,
      step: 0.1,
      defaultValue: 1,
    },
    {
      key: 'autoRotateX',
      label: 'Auto Rotate X',
      type: 'boolean',
      defaultValue: false,
    },
    {
      key: 'autoRotateY',
      label: 'Auto Rotate Y',
      type: 'boolean',
      defaultValue: false,
    },
    {
      key: 'autoRotateZ',
      label: 'Auto Rotate Z',
      type: 'boolean',
      defaultValue: false,
    },
    // --- SEKCJA 2: GEOMETRIA SIATKI (GRID) ---
    {
      key: 'X_SIZE',
      label: 'X size',
      type: 'number',
      min: 1,
      max: 100,
      step: 1,
      defaultValue: 20,
    },
    {
      key: 'Y_SIZE',
      label: 'Y size',
      type: 'number',
      min: 1,
      max: 100,
      step: 1,
      defaultValue: 20,
    },
    {
      key: 'Z_SIZE',
      label: 'Z size',
      type: 'number',
      min: 1,
      max: 100,
      step: 1,
      defaultValue: 20,
    },

    {
      key: 'X_ROWS',
      label: 'X rows',
      type: 'number',
      min: 2,
      max: 35,
      step: 1,
      defaultValue: 10,
    },
    {
      key: 'Y_ROWS',
      label: 'Y rows',
      type: 'number',
      min: 2,
      max: 35,
      step: 1,
      defaultValue: 10,
    },
    {
      key: 'Z_ROWS',
      label: 'Z rows',
      type: 'number',
      min: 2,
      max: 35,
      step: 1,
      defaultValue: 10,
    },

    {
      key: 'X_GAP',
      label: 'X gap',
      type: 'number',
      min: 0,
      max: 100,
      step: 1,
      defaultValue: 1,
    },
    {
      key: 'Y_GAP',
      label: 'Y gap',
      type: 'number',
      min: 0,
      max: 100,
      step: 1,
      defaultValue: 1,
    },
    {
      key: 'Z_GAP',
      label: 'Z gap',
      type: 'number',
      min: 0,
      max: 100,
      step: 1,
      defaultValue: 1,
    },

    {
      key: 'X_ROTATE',
      label: 'X rotate',
      type: 'number',
      min: 0,
      max: 360,
      step: 1,
      defaultValue: 0,
    },
    {
      key: 'Y_ROTATE',
      label: 'Y rotate',
      type: 'number',
      min: 0,
      max: 360,
      step: 1,
      defaultValue: 0,
    },
    {
      key: 'Z_ROTATE',
      label: 'Z rotate',
      type: 'number',
      min: 0,
      max: 360,
      step: 1,
      defaultValue: 0,
    },
    // --- SEKCJA 3: WIDOCZNOŚĆ ŚCIAN ---
    {
      key: 'showFrontWall',
      label: 'Front wall',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'showBackWall',
      label: 'Back wall',
      type: 'boolean',
      defaultValue: true,
    },
    // HZ SLIDER 
    {
      key: 'Front&BackHZRangeMin',
      label: 'Front and Back HZ range MIN',
      type: 'number',
      min: 0,
      max: 12000,
      step: 1,
      defaultValue: 2500,
    },
    {
      key: 'Front&BackHZRangeMax',
      label: 'Front and Back HZ range MAX',
      type: 'number',
      min: 0,
      max: 12000,
      step: 1,
      defaultValue: 12000,
    },
    {
      key: 'showLeftWall',
      label: 'Left wall',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'showRightWall',
      label: 'Right wall',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'Left&RightHZRangeMin',
      label: 'Left and Right HZ range MIN',
      type: 'number',
      min: 0,
      max: 12000,
      step: 1,
      defaultValue: 35,
    },
    {
      key: 'Left&RightHZRangeMax',
      label: 'Left and Right HZ range MAX',
      type: 'number',
      min: 0,
      max: 12000,
      step: 1,
      defaultValue: 260,
    },
    {
      key: 'showTopWall',
      label: 'Top wall',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'showBottomWall',
      label: 'Bottom wall',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'TopBottomHZRangeMin',
      label: 'Top and Bottom HZ range MIN',
      type: 'number',
      min: 0,
      max: 12000,
      step: 1,
      defaultValue: 260,
    },
    {
      key: 'TopBottomHZRangeMax',
      label: 'Top and Bottom HZ range MAX',
      type: 'number',
      min: 0,
      max: 12000,
      step: 1,
      defaultValue: 2500,
    },
    // --- SEKCJA 4: REAKTYWNOŚĆ AUDIO ---
    {
      key: 'audioDepth',
      label: 'Audio intensity',
      type: 'number',
      min: 0,
      max: 500,
      step: 1,
      defaultValue: 250,
    },
    {
      key: 'sidePulseMult',
      label: 'Pulse Mult: Sides',
      type: 'number',
      min: 0,
      max: 5,
      step: 0.1,
      defaultValue: 1,
    },
    {
      key: 'topBottomPulseMult',
      label: 'Pulse Mult: T/B',
      type: 'number',
      min: 0,
      max: 5,
      step: 0.1,
      defaultValue: 1,
    },
    {
      key: 'frontBackPulseMult',
      label: 'Pulse Mult: F/B',
      type: 'number',
      min: 0,
      max: 5,
      step: 0.1,
      defaultValue: 1,
    },
    {
      key: 'pulseSmLR',
      label: 'Pulse Smooth: L/R',
      type: 'number',
      min: 0.001,
      max: 1,
      step: 0.001,
      defaultValue: 0.57,
    },
    {
      key: 'spectrumSmLR',
      label: 'Spec Smooth: L/R',
      type: 'number',
      min: 0.001,
      max: 1,
      step: 0.001,
      defaultValue: 0.1,
    },
    {
      key: 'pulseSmTB',
      label: 'Pulse Smooth: T/B',
      type: 'number',
      min: 0.001,
      max: 1,
      step: 0.001,
      defaultValue: 0.34,
    },
    {
      key: 'spectrumSmTB',
      label: 'Spec Smooth: T/B',
      type: 'number',
      min: 0.001,
      max: 1,
      step: 0.001,
      defaultValue: 0.10,
    },
    {
      key: 'pulseSmFB',
      label: 'Pulse Smooth: F/B',
      type: 'number',
      min: 0.001,
      max: 1,
      step: 0.001,
      defaultValue: 0.5,
    },
    {
      key: 'spectrumSmFB',
      label: 'Spec Smooth: F/B',
      type: 'number',
      min: 0.001,
      max: 1,
      step: 0.001,
      defaultValue: 0.43,
    },
    // --- SEKCJA 5: KOLORY I ŚWIATŁO ---
    {
      key: 'trailAlpha',
      label: 'Trail alpha',
      type: 'number',
      min: 8,
      max: 255,
      step: 1,
      defaultValue: 255,
    },
    {
      key: 'trailMode',
      label: 'Trail mode',
      type: 'select',
      options: ['solid', 'gradient'],
      defaultValue: 'solid',
    },
    {
      key: 'scanlineAmount',
      label: 'Scanline amount',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.35,
    },
    {
      key: 'scanlineCount',
      label: 'Scanline count',
      type: 'number',
      min: 0.05,
      max: 1.5,
      step: 0.01,
      defaultValue: 0.48,
    },
    {
      key: 'dynamicLight',
      label: 'Dynamic light',
      type: 'boolean',
      defaultValue: false,
    },
    {
      key: 'hue',
      label: 'Hue',
      type: 'number',
      min: 0,
      max: 360,
      step: 1,
      defaultValue: 216,
    },
    {
      key: 'colorSpread',
      label: 'Color spread',
      type: 'number',
      min: 0,
      max: 360,
      step: 1,
      defaultValue: 18,
    },
    {
      key: 'saturation',
      label: 'Saturation',
      type: 'number',
      min: 0,
      max: 100,
      step: 1,
      defaultValue: 68,
    },
    {
      key: 'brightness',
      label: 'Brightness',
      type: 'number',
      min: 0,
      max: 100,
      step: 1,
      defaultValue: 96,
    },
    {
      key: 'opacity',
      label: 'Opacity',
      type: 'number',
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 255,
    },
    // --- SEKCJA 6: KRAWĘDZIE I WYRÓWNANIE ---
    {
      key: 'edgeWeight',
      label: 'Edge weight',
      type: 'number',
      min: 0,
      max: 4,
      step: 0.1,
      defaultValue: 1.3,
    },
    {
      key: 'edgeAlpha',
      label: 'Edge alpha',
      type: 'number',
      min: 0,
      max: 255,
      step: 1,
      defaultValue: 255,
    },
    {
      key: 'frontBackEdgeAlign',
      label: 'F/B edge align',
      type: 'boolean',
      defaultValue: false,
    },
    {
      key: 'frontBackEdgeAlignAmount',
      label: 'F/B align amount',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.8,
    },
    {
      key: 'frontBackEdgeAlignRadius',
      label: 'F/B align radius',
      type: 'number',
      min: 0.05,
      max: 1,
      step: 0.01,
      defaultValue: 0.75,
    },
    {
      key: 'leftRightEdgeAlign',
      label: 'L/R edge align',
      type: 'boolean',
      defaultValue: false,
    },
    {
      key: 'leftRightEdgeAlignAmount',
      label: 'L/R align amount',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.8,
    },
    {
      key: 'leftRightEdgeAlignRadius',
      label: 'L/R align radius',
      type: 'number',
      min: 0.05,
      max: 1,
      step: 0.01,
      defaultValue: 0.75,
    },
    {
      key: 'topBottomEdgeAlign',
      label: 'T/B edge align',
      type: 'boolean',
      defaultValue: false,
    },
    {
      key: 'topBottomEdgeAlignAmount',
      label: 'T/B align amount',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.8,
    },
    {
      key: 'topBottomEdgeAlignRadius',
      label: 'T/B align radius',
      type: 'number',
      min: 0.05,
      max: 1,
      step: 0.01,
      defaultValue: 0.75,
    },
    // --- SEKCJA 7: ARCH STRENGTH (FORMUŁY) ---
    {
      key: 'frontBackArch',
      label: 'F/B Arch Strength',
      type: 'number',
      min: -4,
      max: 4,
      step: 0.01,
      defaultValue: 1.5,
    },
    {
      key: 'frontBackWallPower',
      label: 'F/B Wall Power',
      type: 'number',
      min: 0,
      max: 4,
      step: 0.01,
      defaultValue: 1,
    },
    {
      key: 'leftRightArch',
      label: 'L/R Arch Strength',
      type: 'number',
      min: -4,
      max: 4,
      step: 0.01,
      defaultValue: 0.5,
    },
    {
      key: 'leftRightWallPower',
      label: 'L/R Wall Power',
      type: 'number',
      min: 0,
      max: 4,
      step: 0.01,
      defaultValue: 1,
    },
    {
      key: 'topBottomArch',
      label: 'T/B Arch Strength',
      type: 'number',
      min: -4,
      max: 4,
      step: 0.01,
      defaultValue: 0.5,
    },
    {
      key: 'topBottomWallPower',
      label: 'T/B Wall Power',
      type: 'number',
      min: 0,
      max: 4,
      step: 0.01,
      defaultValue: 1,
    },
    {
      key: 'archMasterLink',
      label: 'Link Arch Strength',
      type: 'boolean',
      defaultValue: false,
    },
    {
      key: 'archMasterOffset',
      label: 'Arch Master Offset',
      type: 'number',
      min: -10,
      max: 10,
      step: 0.01,
      defaultValue: 0,
    },
    {
      key: 'sinDensity',
      label: 'Arch Sin Density',
      type: 'number',
      min: 0,
      max: 10,
      step: 0.01,
      defaultValue: 0,
    },
    {
      key: 'sinPhase',
      label: 'Arch Sin Phase',
      type: 'number',
      min: -3.14,
      max: 3.14,
      step: 0.01,
      defaultValue: 0,
    },
  ];
